# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del autor: ', max_length=50)),
                ('surname', models.CharField(help_text='Ingrese el apellido del author: ', max_length=50)),
                ('bday', models.DateField(help_text='Selecciona la fecha de nacimiento: ')),
                ('genere', models.CharField(help_text='Ingrese su genero: ', max_length=50)),
                ('email', models.EmailField(help_text='Ingrese su e-mail: ', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titulo de la pelicula: ', max_length=50)),
                ('company', models.CharField(help_text='Nombre de la compañia productora: ', max_length=50)),
                ('pubdate', models.DateField(help_text='Fecha de pelicula: ')),
                ('director', models.CharField(help_text='Director de la pelicula: ', max_length=50)),
                ('category', models.CharField(help_text='Categorias de la pelicula: ', max_length=50)),
                ('sipnosis', models.CharField(help_text='Sipnosis de la pelicula: ', max_length=50)),
                ('review', models.CharField(help_text='Opinion de la cinta: ', max_length=500)),
                ('stars', models.DecimalField(decimal_places=2, help_text='Puntuacion que le damos: ', max_digits=10)),
            ],
        ),
    ]
